INSERT INTO SHINE_POST (POST_TYPE, BODY, CREATED_TIMESTAMP, TITLE, VIEW_COUNT, VOTE)
VALUES ('QUESTION', 'Sample question body 1', CURRENT_TIMESTAMP(), 'Sample Title 1', 0, 0);

INSERT INTO SHINE_POST (POST_TYPE, BODY, CREATED_TIMESTAMP, TITLE, VIEW_COUNT, VOTE)
VALUES ('QUESTION', 'Sample question body 2', CURRENT_TIMESTAMP(), 'Sample Title 2', 0, 0);

INSERT INTO SHINE_POST (POST_TYPE, BODY, CREATED_TIMESTAMP, TITLE, VIEW_COUNT, VOTE)
VALUES ('QUESTION', 'Sample question body 3', CURRENT_TIMESTAMP(), 'Sample Title 3', 0, 0);

