-- QUESTION POST
INSERT INTO SHINE_POST (ID, POST_TYPE, BODY, CREATED_TIMESTAMP, TITLE, VIEW_COUNT, VOTE)
VALUES (-1, 'QUESTION', 'Sample question body 1', CURRENT_TIMESTAMP() + 0, 'Sample Title 1', 0, 0);

INSERT INTO SHINE_POST (ID, POST_TYPE, BODY, CREATED_TIMESTAMP, TITLE, VIEW_COUNT, VOTE)
VALUES (-2, 'QUESTION', 'Sample question body 2', CURRENT_TIMESTAMP() + 1, 'Sample Title 2', 0, 0);

INSERT INTO SHINE_POST (ID, POST_TYPE, BODY, CREATED_TIMESTAMP, TITLE, VIEW_COUNT, VOTE)
VALUES (-3, 'QUESTION', 'Sample question body 3', CURRENT_TIMESTAMP() + 2, 'Sample Title 3', 0, 0);



-- ANSWER POST
INSERT INTO SHINE_POST (POST_TYPE, BODY, CREATED_TIMESTAMP,  VIEW_COUNT, VOTE, QUESTION_ID)
VALUES ('ANSWER', 'Sample answer body 1', CURRENT_TIMESTAMP() + 0,  0, 0, -1);

INSERT INTO SHINE_POST (POST_TYPE, BODY, CREATED_TIMESTAMP,  VIEW_COUNT, VOTE, QUESTION_ID)
VALUES ('ANSWER', 'Sample answer body 2', CURRENT_TIMESTAMP() + 1,  0, 0, -2);

INSERT INTO SHINE_POST (POST_TYPE, BODY, CREATED_TIMESTAMP,  VIEW_COUNT, VOTE, QUESTION_ID)
VALUES ('ANSWER', 'Sample answer body 3', CURRENT_TIMESTAMP() + 2,  0, 0, -3);




