INSERT INTO SHINE_SEARCH_FIELD (ID, ENTITY_TYPE, PROPERTY_NAME, ABBREVIATION, FRIENDLY_NAME)
VALUES (1, 'POST', 'body', 'q', 'Post Body');

INSERT INTO SHINE_SEARCH_FIELD (ID, ENTITY_TYPE, PROPERTY_NAME, ABBREVIATION, FRIENDLY_NAME)
VALUES (2, 'POST', 'editedTimeStamp', 'recent', 'Recent Post');

INSERT INTO SHINE_SEARCH_FIELD (ID, ENTITY_TYPE, PROPERTY_NAME, ABBREVIATION, FRIENDLY_NAME)
VALUES (3, 'POST', 'postType', 'postType', 'Post Type');

INSERT INTO SHINE_SEARCH_FIELD (ID, ENTITY_TYPE, PROPERTY_NAME, ABBREVIATION, FRIENDLY_NAME)
VALUES (4, 'POST', 'vote', 'vote', 'Post Vote');

INSERT INTO SHINE_SEARCH_FIELD (ID, ENTITY_TYPE, PROPERTY_NAME, ABBREVIATION, FRIENDLY_NAME)
VALUES (5, 'Question', 'answerCount', 'answerCount', 'Answer Count');






