INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT) VALUES (0,'java',0);
INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT) VALUES (1,'programming',0);
INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT) VALUES (2,'html',0);
INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT) VALUES (3,'c++',0);
