INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-1, 'java', 0);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-2, 'programming', 0);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-3, 'html', 5);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-4, 'C++', 10);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-5, 'object-Oriented', 10);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-6, 'JavaScript', 10);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-7, 'Database', 6);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-8, 'sql', 7);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-9, 'groovy', 8);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-10, 'Scala', 10);


