INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-1, 'java', 0);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-2, 'programming', 0);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-3, 'html', 5);

INSERT INTO SHINE_TAG (ID, NAME, USED_COUNT)
VALUES (-4, 'c++', 10);


